2021-04-20T18:30:55.622379+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-04-20T18:30:55.622821+00:00 app[web.1]: npm ERR! errno 1
2021-04-20T18:30:55.632845+00:00 app[web.1]: npm ERR! cohort11a-capstone-web@0.1.0 start: `react-scripts start`
2021-04-20T18:30:55.633052+00:00 app[web.1]: npm ERR! Exit status 1
2021-04-20T18:30:55.633316+00:00 app[web.1]: npm ERR!
2021-04-20T18:30:55.633554+00:00 app[web.1]: npm ERR! Failed at the cohort11a-capstone-web@0.1.0 start script.
2021-04-20T18:30:55.633773+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-20T18:30:56.059778+00:00 app[web.1]: 
2021-04-20T18:30:56.060280+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-04-20T18:30:56.061245+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-04-20T18_30_55_635Z-debug.log
2021-04-20T18:30:56.132920+00:00 heroku[web.1]: Process exited with status 1
2021-04-20T18:30:56.232904+00:00 heroku[web.1]: State changed from up to crashed
2021-04-20T18:30:56.273073+00:00 heroku[web.1]: State changed from crashed to starting
2021-04-20T18:31:09.555064+00:00 heroku[web.1]: Starting process with command `npm start`
2021-04-20T18:31:11.706325+00:00 app[web.1]: 
2021-04-20T18:31:11.706349+00:00 app[web.1]: > cohort11a-capstone-web@0.1.0 start /app
2021-04-20T18:31:11.706350+00:00 app[web.1]: > react-scripts start
2021-04-20T18:31:11.706350+00:00 app[web.1]: 
2021-04-20T18:31:14.602644+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: Project is running at http://172.16.199.18/
2021-04-20T18:31:14.603275+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: webpack output is served from
2021-04-20T18:31:14.603342+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: Content not from webpack is served from /app/public
2021-04-20T18:31:14.603408+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: 404s will fallback to /
2021-04-20T18:31:14.604052+00:00 app[web.1]: Starting the development server...
2021-04-20T18:31:14.604054+00:00 app[web.1]: 
2021-04-20T18:31:15.041383+00:00 heroku[web.1]: State changed from starting to up
2021-04-20T18:32:03.467478+00:00 app[web.1]: 
2021-04-20T18:32:03.467491+00:00 app[web.1]: <--- Last few GCs --->
2021-04-20T18:32:03.467492+00:00 app[web.1]: 
2021-04-20T18:32:03.467499+00:00 app[web.1]: [28:0x63650a0]    51357 ms: Mark-sweep (reduce) 252.4 (261.0) -> 251.7 (260.2) MB, 311.2 / 0.0 ms  (average mu = 0.236, current mu = 0.000) last resort GC in old space requested
2021-04-20T18:32:03.467499+00:00 app[web.1]: [28:0x63650a0]    51672 ms: Mark-sweep (reduce) 251.7 (259.2) -> 251.6 (260.2) MB, 314.7 / 0.0 ms  (average mu = 0.135, current mu = 0.000) last resort GC in old space requested
2021-04-20T18:32:03.467500+00:00 app[web.1]: 
2021-04-20T18:32:03.467500+00:00 app[web.1]: 
2021-04-20T18:32:03.467501+00:00 app[web.1]: <--- JS stacktrace --->
2021-04-20T18:32:03.467501+00:00 app[web.1]: 
2021-04-20T18:32:03.467507+00:00 app[web.1]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2021-04-20T18:32:03.468125+00:00 app[web.1]: 1: 0xa04200 node::Abort() [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.468569+00:00 app[web.1]: 2: 0x94e4e9 node::FatalError(char const*, char const*) [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.469066+00:00 app[web.1]: 3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.469566+00:00 app[web.1]: 4: 0xb79b07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.470124+00:00 app[web.1]: 5: 0xd34395  [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.470690+00:00 app[web.1]: 6: 0xd46c01 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.471288+00:00 app[web.1]: 7: 0xd1524b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.471945+00:00 app[web.1]: 8: 0x105b23f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.472640+00:00 app[web.1]: 9: 0x1401219  [/app/.heroku/node/bin/node]
2021-04-20T18:32:03.510188+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-04-20T18:32:03.510584+00:00 app[web.1]: npm ERR! errno 1
2021-04-20T18:32:03.515582+00:00 app[web.1]: npm ERR! cohort11a-capstone-web@0.1.0 start: `react-scripts start`
2021-04-20T18:32:03.515717+00:00 app[web.1]: npm ERR! Exit status 1
2021-04-20T18:32:03.515871+00:00 app[web.1]: npm ERR!
2021-04-20T18:32:03.515993+00:00 app[web.1]: npm ERR! Failed at the cohort11a-capstone-web@0.1.0 start script.
2021-04-20T18:32:03.516115+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-20T18:32:03.526289+00:00 app[web.1]: 
2021-04-20T18:32:03.526483+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-04-20T18:32:03.526606+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-04-20T18_32_03_516Z-debug.log
2021-04-20T18:32:03.596107+00:00 heroku[web.1]: Process exited with status 1
2021-04-20T18:32:03.656039+00:00 heroku[web.1]: State changed from up to crashed
2021-04-20T18:56:49.685182+00:00 heroku[web.1]: State changed from crashed to starting
2021-04-20T18:57:02.573207+00:00 heroku[web.1]: Starting process with command `npm start`
2021-04-20T18:57:04.739079+00:00 app[web.1]: 
2021-04-20T18:57:04.739102+00:00 app[web.1]: > cohort11a-capstone-web@0.1.0 start /app
2021-04-20T18:57:04.739102+00:00 app[web.1]: > react-scripts start
2021-04-20T18:57:04.739103+00:00 app[web.1]: 
2021-04-20T18:57:08.088249+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: Project is running at http://172.16.215.162/
2021-04-20T18:57:08.088590+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: webpack output is served from
2021-04-20T18:57:08.088665+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: Content not from webpack is served from /app/public
2021-04-20T18:57:08.088730+00:00 app[web.1]: [34mâ„¹[39m [90mï½¢wdsï½£[39m: 404s will fallback to /
2021-04-20T18:57:08.089402+00:00 app[web.1]: Starting the development server...
2021-04-20T18:57:08.089403+00:00 app[web.1]: 
2021-04-20T18:57:08.548768+00:00 heroku[web.1]: State changed from starting to up
2021-04-20T18:57:59.206071+00:00 app[web.1]: 
2021-04-20T18:57:59.206086+00:00 app[web.1]: <--- Last few GCs --->
2021-04-20T18:57:59.206087+00:00 app[web.1]: 
2021-04-20T18:57:59.206106+00:00 app[web.1]: [28:0x54c80a0]    54159 ms: Mark-sweep (reduce) 252.6 (261.2) -> 252.3 (261.2) MB, 231.1 / 0.0 ms  (average mu = 0.289, current mu = 0.000) last resort GC in old space requested
2021-04-20T18:57:59.206106+00:00 app[web.1]: [28:0x54c80a0]    54381 ms: Mark-sweep (reduce) 252.3 (260.2) -> 252.2 (261.2) MB, 222.7 / 0.0 ms  (average mu = 0.175, current mu = 0.000) last resort GC in old space requested
2021-04-20T18:57:59.206107+00:00 app[web.1]: 
2021-04-20T18:57:59.206107+00:00 app[web.1]: 
2021-04-20T18:57:59.206108+00:00 app[web.1]: <--- JS stacktrace --->
2021-04-20T18:57:59.206108+00:00 app[web.1]: 
2021-04-20T18:57:59.206117+00:00 app[web.1]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2021-04-20T18:57:59.206891+00:00 app[web.1]: 1: 0xa04200 node::Abort() [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.207377+00:00 app[web.1]: 2: 0x94e4e9 node::FatalError(char const*, char const*) [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.207872+00:00 app[web.1]: 3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.208552+00:00 app[web.1]: 4: 0xb79b07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.209239+00:00 app[web.1]: 5: 0xd34395  [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.209852+00:00 app[web.1]: 6: 0xd46c01 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.210493+00:00 app[web.1]: 7: 0xd1524b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.211280+00:00 app[web.1]: 8: 0x105b23f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.212065+00:00 app[web.1]: 9: 0x1401219  [/app/.heroku/node/bin/node]
2021-04-20T18:57:59.252598+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-04-20T18:57:59.252986+00:00 app[web.1]: npm ERR! errno 1
2021-04-20T18:57:59.258013+00:00 app[web.1]: npm ERR! cohort11a-capstone-web@0.1.0 start: `react-scripts start`
2021-04-20T18:57:59.258142+00:00 app[web.1]: npm ERR! Exit status 1
2021-04-20T18:57:59.258290+00:00 app[web.1]: npm ERR!
2021-04-20T18:57:59.258423+00:00 app[web.1]: npm ERR! Failed at the cohort11a-capstone-web@0.1.0 start script.
2021-04-20T18:57:59.258557+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-20T18:57:59.265921+00:00 app[web.1]: 
2021-04-20T18:57:59.266051+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-04-20T18:57:59.266118+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-04-20T18_57_59_259Z-debug.log
2021-04-20T18:57:59.314806+00:00 heroku[web.1]: Process exited with status 1
2021-04-20T18:57:59.373349+00:00 heroku[web.1]: State changed from up to crashed
